// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

#ifndef PROTOBUF_Person_2eproto__INCLUDED
#define PROTOBUF_Person_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Person_2eproto();
void protobuf_AssignDesc_Person_2eproto();
void protobuf_ShutdownFile_Person_2eproto();

class PBPersonAttribute;
class PBPerson;

// ===================================================================

class PBPersonAttribute : public ::google::protobuf::MessageLite {
 public:
  const google::protobuf::FieldInfo* GetFieldInfoArray(int& count) const;
  PBPersonAttribute();
  virtual ~PBPersonAttribute();

  private:
  PBPersonAttribute(const PBPersonAttribute& from);

  inline PBPersonAttribute& operator=(const PBPersonAttribute& from);
  public:


  // implements Message ----------------------------------------------

  PBPersonAttribute* New() const;
  void CopyFrom(const PBPersonAttribute& from);
  void MergeFrom(const PBPersonAttribute& from);
  bool IsInitialized() const;

  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string key = 1;
  inline bool has_key() const;
  inline void clear_key();
  inline const ::std::string& key() const;
  inline void set_key(const ::std::string& value);
  inline ::std::string* mutable_key();

  // required string value = 2;
  inline bool has_value() const;
  inline void clear_value();
  inline const ::std::string& value() const;
  inline void set_value(const ::std::string& value);
  inline ::std::string* mutable_value();

  // @@protoc_insertion_point(class_scope:PBPersonAttribute)
 private:
  inline void set_has_key();
  inline void clear_has_key();
  inline void set_has_value();
  inline void clear_has_value();

  ::std::string* key_;
  ::std::string* value_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_Person_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_Person_2eproto();
  #endif
  friend void protobuf_AssignDesc_Person_2eproto();
  friend void protobuf_ShutdownFile_Person_2eproto();

};
// -------------------------------------------------------------------

class PBPerson : public ::google::protobuf::MessageLite {
 public:
  const google::protobuf::FieldInfo* GetFieldInfoArray(int& count) const;
  PBPerson();
  virtual ~PBPerson();

  private:
  PBPerson(const PBPerson& from);

  inline PBPerson& operator=(const PBPerson& from);
  public:


  // implements Message ----------------------------------------------

  PBPerson* New() const;
  void CopyFrom(const PBPerson& from);
  void MergeFrom(const PBPerson& from);
  bool IsInitialized() const;

  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline ::std::string* mutable_name();

  // optional int32 age = 2;
  inline bool has_age() const;
  inline void clear_age();
  inline ::google::protobuf::int32 age() const;
  inline void set_age(::google::protobuf::int32 value);

  // optional int32 sex = 3;
  inline bool has_sex() const;
  inline void clear_sex();
  inline ::google::protobuf::int32 sex() const;
  inline void set_sex(::google::protobuf::int32 value);

  // optional string phone = 4;
  inline bool has_phone() const;
  inline void clear_phone();
  inline const ::std::string& phone() const;
  inline void set_phone(const ::std::string& value);
  inline ::std::string* mutable_phone();

  // repeated .PBPerson children = 5;
  inline int children_size() const;
  inline void clear_children();
  inline const ::PBPerson& children(int index) const;
  inline ::PBPerson* mutable_children(int index);
  inline ::PBPerson* add_children();
  inline const ::google::protobuf::RepeatedPtrField< ::PBPerson >&
      children() const;
  inline ::google::protobuf::RepeatedPtrField< ::PBPerson >*
      mutable_children();

  // repeated .PBPersonAttribute attributes = 6;
  inline int attributes_size() const;
  inline void clear_attributes();
  inline const ::PBPersonAttribute& attributes(int index) const;
  inline ::PBPersonAttribute* mutable_attributes(int index);
  inline ::PBPersonAttribute* add_attributes();
  inline const ::google::protobuf::RepeatedPtrField< ::PBPersonAttribute >&
      attributes() const;
  inline ::google::protobuf::RepeatedPtrField< ::PBPersonAttribute >*
      mutable_attributes();

  // @@protoc_insertion_point(class_scope:PBPerson)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_age();
  inline void clear_has_age();
  inline void set_has_sex();
  inline void clear_has_sex();
  inline void set_has_phone();
  inline void clear_has_phone();

  ::std::string* name_;
  ::google::protobuf::int32 age_;
  ::google::protobuf::int32 sex_;
  ::std::string* phone_;
  ::google::protobuf::RepeatedPtrField< ::PBPerson > children_;
  ::google::protobuf::RepeatedPtrField< ::PBPersonAttribute > attributes_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_Person_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_Person_2eproto();
  #endif
  friend void protobuf_AssignDesc_Person_2eproto();
  friend void protobuf_ShutdownFile_Person_2eproto();

};
// ===================================================================


// ===================================================================

// PBPersonAttribute

// required string key = 1;
inline bool PBPersonAttribute::has_key() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PBPersonAttribute::set_has_key() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PBPersonAttribute::clear_has_key() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PBPersonAttribute::clear_key() {
  if (key_ != &::google::protobuf::internal::kEmptyString) {
    key_->clear();
  }
  clear_has_key();
}
inline const ::std::string& PBPersonAttribute::key() const {
  return *key_;
}
inline void PBPersonAttribute::set_key(const ::std::string& value) {
  set_has_key();
  if (key_ == &::google::protobuf::internal::kEmptyString) {
    key_ = new ::std::string;
  }
  key_->assign(value);
}
inline ::std::string* PBPersonAttribute::mutable_key() {
  set_has_key();
  if (key_ == &::google::protobuf::internal::kEmptyString) {
    key_ = new ::std::string;
  }
  return key_;
}

// required string value = 2;
inline bool PBPersonAttribute::has_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PBPersonAttribute::set_has_value() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PBPersonAttribute::clear_has_value() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PBPersonAttribute::clear_value() {
  if (value_ != &::google::protobuf::internal::kEmptyString) {
    value_->clear();
  }
  clear_has_value();
}
inline const ::std::string& PBPersonAttribute::value() const {
  return *value_;
}
inline void PBPersonAttribute::set_value(const ::std::string& value) {
  set_has_value();
  if (value_ == &::google::protobuf::internal::kEmptyString) {
    value_ = new ::std::string;
  }
  value_->assign(value);
}
inline ::std::string* PBPersonAttribute::mutable_value() {
  set_has_value();
  if (value_ == &::google::protobuf::internal::kEmptyString) {
    value_ = new ::std::string;
  }
  return value_;
}

// -------------------------------------------------------------------

// PBPerson

// optional string name = 1;
inline bool PBPerson::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PBPerson::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PBPerson::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PBPerson::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& PBPerson::name() const {
  return *name_;
}
inline void PBPerson::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline ::std::string* PBPerson::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}

// optional int32 age = 2;
inline bool PBPerson::has_age() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PBPerson::set_has_age() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PBPerson::clear_has_age() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PBPerson::clear_age() {
  age_ = 0;
  clear_has_age();
}
inline ::google::protobuf::int32 PBPerson::age() const {
  return age_;
}
inline void PBPerson::set_age(::google::protobuf::int32 value) {
  set_has_age();
  age_ = value;
}

// optional int32 sex = 3;
inline bool PBPerson::has_sex() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PBPerson::set_has_sex() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PBPerson::clear_has_sex() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PBPerson::clear_sex() {
  sex_ = 0;
  clear_has_sex();
}
inline ::google::protobuf::int32 PBPerson::sex() const {
  return sex_;
}
inline void PBPerson::set_sex(::google::protobuf::int32 value) {
  set_has_sex();
  sex_ = value;
}

// optional string phone = 4;
inline bool PBPerson::has_phone() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PBPerson::set_has_phone() {
  _has_bits_[0] |= 0x00000008u;
}
inline void PBPerson::clear_has_phone() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void PBPerson::clear_phone() {
  if (phone_ != &::google::protobuf::internal::kEmptyString) {
    phone_->clear();
  }
  clear_has_phone();
}
inline const ::std::string& PBPerson::phone() const {
  return *phone_;
}
inline void PBPerson::set_phone(const ::std::string& value) {
  set_has_phone();
  if (phone_ == &::google::protobuf::internal::kEmptyString) {
    phone_ = new ::std::string;
  }
  phone_->assign(value);
}
inline ::std::string* PBPerson::mutable_phone() {
  set_has_phone();
  if (phone_ == &::google::protobuf::internal::kEmptyString) {
    phone_ = new ::std::string;
  }
  return phone_;
}

// repeated .PBPerson children = 5;
inline int PBPerson::children_size() const {
  return children_.size();
}
inline void PBPerson::clear_children() {
  children_.Clear();
}
inline const ::PBPerson& PBPerson::children(int index) const {
  return children_.Get(index);
}
inline ::PBPerson* PBPerson::mutable_children(int index) {
  return children_.Mutable(index);
}
inline ::PBPerson* PBPerson::add_children() {
  return children_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::PBPerson >&
PBPerson::children() const {
  return children_;
}
inline ::google::protobuf::RepeatedPtrField< ::PBPerson >*
PBPerson::mutable_children() {
  return &children_;
}

// repeated .PBPersonAttribute attributes = 6;
inline int PBPerson::attributes_size() const {
  return attributes_.size();
}
inline void PBPerson::clear_attributes() {
  attributes_.Clear();
}
inline const ::PBPersonAttribute& PBPerson::attributes(int index) const {
  return attributes_.Get(index);
}
inline ::PBPersonAttribute* PBPerson::mutable_attributes(int index) {
  return attributes_.Mutable(index);
}
inline ::PBPersonAttribute* PBPerson::add_attributes() {
  return attributes_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::PBPersonAttribute >&
PBPerson::attributes() const {
  return attributes_;
}
inline ::google::protobuf::RepeatedPtrField< ::PBPersonAttribute >*
PBPerson::mutable_attributes() {
  return &attributes_;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Person_2eproto__INCLUDED
